pipeline:
  identifier: Build_shiftleft_c_demo_1696271206370
  name: HAR-Qwiet-c
  orgIdentifier: default
  projectIdentifier: HARQwietc
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695829315182
        repoName: shiftleft-c-demo
  stages:
    - stage:
        identifier: build
        name: Build and Test
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: SL Analyze
                  identifier: SL_Analyze
                  spec:
                    connectorRef: DOCQwietc
                    image: shiftleft/core:latest
                    shell: Sh
                    command: sl analyze --app HAR-Qwiet-c
                    envVariables:
                      SHIFTLEFT_ACCESS_TOKEN: <+secrets.getValue("SHIFTLEFT_ACCESS_TOKEN")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
  tags: {}
